services:
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: productos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./appStore/deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  appstore:
    build:
      context: ./appStore
      dockerfile: deployment/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
      - rabbitmq
    networks:
      - backend

  appnotification:
    build:
      context: ./appNotification
      dockerfile: deployment/Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
