server:
  port: 8088
spring:
  application:
    name: "appNotification"
  devtools:
    add-properties: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
